kind: Deployment
apiVersion: apps/v1
metadata:
  name: <Nombre>
  namespace: taller
  labels:
    app: <Nombre>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <Nombre>
  template:
    metadata:
      labels:
        app: <Nombre>
    spec:
      containers:
        - name: nodejs
          image: <image-file>
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NAME
              value: reverse-proxy
          volumeMounts:
            - name: site-config
              mountPath: /usr/local/apache2/conf/sites/ 
      volumes:
        - name: site-config
          configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
            name: site-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%



    
